version: "3.9"

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: boxinator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/boxinator
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      AUTH_URL_LOGIN: http://keycloak:8080/realms/Boxinator/protocol/openid-connect/token
      AUTH_URL_REGISTER: http://keycloak:8080/admin/realms/Boxinator/users
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8080/realms/Boxinator

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    volumes:
      - ./data/import:/opt/keycloak/data/import
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: 1234
      KEYCLOAK_USER: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - db
    command:
      - start-dev --import-realm -Dkeycloak.migration.strategy=OVERWRITE_EXISTING